#!/bin/bash

__source_d=../sources
__build_d=../build
__build_t=Debug

if [ "$1" == "-c" -o "$1" == "--clean" ]
then
  shift
  rm -rf "${__build_d}"

fi


if [ ! -d "${__build_d}" ]
then
  mkdir -p "${__build_d}"

fi

cd ${__build_d}
cmake -DGOOGLE_TEST_HOME=${GOOGLE_TEST_HOME} -DBOOST_HOME=${BOOST_HOME} -DCMAKE_BUILD_TYPE=${__build_t} -G "Unix Makefiles" ${__source_d}
make $1

